name: Publish to Test PyPI.org
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    # Only publish from the origin repository, not forks
    # if: github.repository_owner == 'stravalib'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}