name:  ðŸ“ Documentation Improvement
description: Report wrong or missing documentation
title: "DOC: "
labels: [documentation]

body:
  - type: checkboxes
    attributes:
      label: Stravalib version checks
      options:
        - label: >
            I have checked that the issue still exists on the latest version of
            the docs [here](https://stravalib.readthedocs.io/en/latest/)
          required: true
  - type: textarea
    id: location
    attributes:
      label: Location of the documentation
      description: >
        Please provide the location of the documentation, e.g. "stravalib.Client" or the
        URL of the documentation, e.g.
        "https://stravalib.readthedocs.io/en/latest/reference/client.htmll"
      placeholder: https://stravalib.readthedocs.io/en/latest/reference/client.html
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Documentation problem
      description: >
        Please provide a description of what documentation you believe needs
        to be fixed/improved
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested fix for documentation
      description: >
        Please explain how the suggested fix improves the stravalib docs.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/stravalib/stravalib/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
