name: Feature Request
description: Suggest an idea for stravalib
title: "ENH: "
labels: [feature-request]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: >
        Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality to stravalib
        - label: >
            Changing existing functionality in stravalib
        - label: >
            Removing existing functionality in stravalib
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve.
      placeholder: >
        I wish I could use stravalib to ...
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented.
        Please use pseudo-code if relevant.
      placeholder: >
        Your text here - pseudo-code demonstrated what this would look like
        when used encouraged
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative Solutions
      description: >
        Please describe any alternative solution (existing functionality,
        3rd party package, etc.) that would satisfy the feature request.
      placeholder: >
        Your text here.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please provide any relevant GitHub issues, code examples or references
        that help describe and support the feature request.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/stravalib/stravalib/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
